version: '3.8'

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_HOST=0.0.0.0
      - LT_PORT=5000
      - LT_DEBUG=false
      - LT_SSL=false
      - LT_UPDATE_MODELS=true
      # Habilitar solo los idiomas que necesitas para mejor rendimiento
      - LT_LOAD_ONLY=en,es,pt,nl
    volumes:
      - lt-data:/app/db
      - lt-models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  lt-data:
  lt-models:
